application: hangman-1263
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: app/static/js

- url: /css
  static_dir: app/static/css

- url: /partials
  static_dir: app/static/partials

- url: /
  static_files: app/index.html
  upload: app/index\.html
  secure: always

- url: /_ah/spi/.*
  script: api.api

- url: /tasks/cache_average_attempts
  script: main.app

- url: /crons/send_reminder
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: endpoints
  version: latest